stages:
  - build
  - publish

build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt
    - python3 setup.py bdist_wheel
  tags:
    - shovel-api
  artifacts:
    paths:
      - dist/*.whl
publish:
  stage: publish
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt
    - python3 setup.py sdist
    - twine upload dist/*
  tags:
    - shovel-api
  rules:
    - if: $CI_COMMIT_TAG
      when: always
