stages:
  - build
  - publish

build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt
    - python3 setup.py bdist_wheel
  after_script:
    - deactivate
    - rm -rf venv
    - rm -rf build
    - rm -rf dist
    - rm -rf diamond_shovel_api.egg-info
  tags:
    - shovel-api
  artifacts:
    paths:
      - dist/*.whl
publish:
  stage: publish
  script:
    - source venv/bin/activate
    - pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt
    - python3 setup.py sdist
    - twine upload dist/*
  after_script:
    - deactivate
    - rm -rf venv
    - rm -rf build
    - rm -rf dist
    - rm -rf diamond_shovel_api.egg-info
  tags:
    - shovel-api
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      when: always
