stages:
  - build

build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - python3 setup.py sdist
    - twine upload dist/*
    - rm -rf dist
    - python3 setup.py bdist_wheel
  artifacts:
    paths:
      - dist/*.whl
