stages:
  - build

build:
  stage: build
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements.txt
    - python3 setup.py sdist
    - twine upload dist/*
    - rm -rf dist
    - python3 setup.py bdist_wheel
  tags:
    - shovel-api

  artifacts:
    paths:
      - dist/*.whl
